apiVersion: v1
kind: Service
metadata:
  name: balancer-service
  namespace: go-balancer
  labels:
    app: balancer
spec:
  type: NodePort
  selector:
    app: balancer
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30081
    protocol: TCP
    name: http
