apiVersion: v1
kind: ConfigMap
metadata:
  name: balancer-config
  namespace: go-balancer
data:
  config.json: |
    {
      "backendname": "backend-service",
      "backendport": 8080,
      "loadbalancerport": 8080,
      "loadbalancermethod": "RoundRobin"
    }
